INSERT INTO PARTNER (NAME, COUNTRY_ID) VALUES ('COMCAST', 2);
INSERT INTO PARTNER (NAME, COUNTRY_ID) VALUES ('SKY', 18);

INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, ADDRESS, PHONE_NUMBER, COUNTRY_ID) VALUES ('Steven', 'H', 'stevenhorngyen@gmail.com', 'Saratoga', '213-631-8152', 2);
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS, ADDRESS, PHONE_NUMBER, COUNTRY_ID) VALUES ('Stephanie', 'C', 'stephanie@gmail.com', 'London', '20-3301-5555', 18);

INSERT INTO USER_HAS_SUBSCRIPTION (USER_ID, PARTNER_ID, START_DATE, END_DATE, CREATED_DATE, SUBSCRIPTION_TYPE_ID) VALUES ('Piccadilly', 'P3', '1Q');
INSERT INTO USER_HAS_SUBSCRIPTION (USER_ID, PARTNER_ID, START_DATE, END_DATE, CREATED_DATE, SUBSCRIPTION_TYPE_ID) VALUES (
	(SELECT USER_ID FROM USER WHERE FIRST_NAME = 'Steven'), 
	(SELECT PARTNER_ID FROM PARTNER WHERE NAME = 'COMCAST' and COUNTRY_ID = 2), 
	sysdate, null, sysdate, 
	SELECT SUBSCRIPTION_TYPE_ID FROM SUBSCRIPTION_TYPE WHERE DESCRIPTION = 'Steven'));

INSERT INTO SUBSCRIPTION_TYPE (SUBSCRIPTION_TYPE_ID, DESCRIPTION) VALUES ('Basic');
INSERT INTO SUBSCRIPTION_TYPE (SUBSCRIPTION_TYPE_ID, DESCRIPTION) VALUES ('Standard');
INSERT INTO SUBSCRIPTION_TYPE (SUBSCRIPTION_TYPE_ID, DESCRIPTION) VALUES ('Premium');
INSERT INTO SUBSCRIPTION_PRICE (SUBSCRIPTION_TYPE_ID, COUNTRY_ID, PRICE) VALUES ('Piccadilly', 'P5', '2D');
INSERT INTO CURRENCY (CURRENCY_ID, DESCRIPTION, COUNTRY_ID) VALUES ('Piccadilly', 'P6', '2D');
INSERT INTO COUNTRY (COUNTRY_ID, DESCRIPTION) VALUES ('Piccadilly', 'P6', '2D');


INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES ((SELECT ROOM_ID FROM ROOM WHERE ROOM_NUMBER = 'C2'), (SELECT GUEST_ID FROM GUEST WHERE LAST_NAME = 'Young'), '2017-01-01');

REATE TABLE PARTNER(
  PARTNER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  COUNTRY_ID INT NOT NULL
);

CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  PHONE_NUMBER VARCHAR(24),
  COUNTRY_ID INT NOT NULL
);

CREATE TABLE USER_HAS_SUBSCRIPTION(
  USER_HAS_SUBSCRIPTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  PARTNER_ID BIGINT NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  CREATED_DATE DATE NOT NULL,
  SUBSCRIPTION_TYPE_ID INT NOT NULL
);

CREATE TABLE SUBSCRIPTION_TYPE(
  SUBSCRIPTION_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY,
  SUBSCRIPTION_TYPE VARCHAR(16) NOT NULL
);


CREATE TABLE SUBSCRIPTION_PRICE(
  SUBSCRIPTION_TYPE_ID NOT NULL,
  COUNTRY_ID INT NOT NULL,
  PRICE FLOAT NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_TYPE_ID, COUNTRY_ID)
);

CREATE TABLE CURRENCY(
  CURRENCY_ID INT PRIMARY KEY,
  DESCRIPTION VARCHAR(16) NOT NULL,
  COUNTRY_ID INT NOT NULL
);

CREATE TABLE COUNTRY(
  COUNTRY_ID INT PRIMARY KEY,
  DESCRIPTION VARCHAR(16) NOT NULL
);