CREATE TABLE PARTNER(
  PARTNER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  COUNTRY_ID INT NOT NULL
);

CREATE TABLE USER(
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  PHONE_NUMBER VARCHAR(24),
  COUNTRY_ID INT NOT NULL
);

CREATE TABLE USER_HAS_SUBSCRIPTION(
  USER_HAS_SUBSCRIPTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  PARTNER_ID BIGINT NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  CREATED_DATE DATE NOT NULL,
  SUBSCRIPTION_TYPE_ID INT NOT NULL
);

CREATE TABLE SUBSCRIPTION_TYPE(
  SUBSCRIPTION_TYPE_ID INT AUTO_INCREMENT PRIMARY KEY,
  DESCRIPTION VARCHAR(16) NOT NULL
);


CREATE TABLE SUBSCRIPTION_PRICE(
  SUBSCRIPTION_TYPE_ID NOT NULL,
  COUNTRY_ID INT NOT NULL,
  PRICE FLOAT NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_TYPE_ID, COUNTRY_ID)
);

CREATE TABLE CURRENCY(
  CURRENCY_ID INT PRIMARY KEY,
  DESCRIPTION VARCHAR(16) NOT NULL,
  COUNTRY_ID INT NOT NULL
);

CREATE TABLE COUNTRY(
  COUNTRY_ID INT PRIMARY KEY,
  DESCRIPTION VARCHAR(16) NOT NULL
);


ALTER TABLE USER_HAS_SUBSCRIPTION ADD FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);
ALTER TABLE USER_HAS_SUBSCRIPTION ADD FOREIGN KEY (PARTNER_ID) REFERENCES PARTNER(PARTNER_ID);
ALTER TABLE USER_HAS_SUBSCRIPTION ADD FOREIGN KEY (SUBSCRIPTION_TYPE_ID) REFERENCES SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID);
CREATE INDEX IDX_START_DATE_ ON USER_HAS_SUBSCRIPTION(START_DATE);

ALTER TABLE SUBSCRIPTION_PRICE ADD FOREIGN KEY (SUBSCRIPTION_TYPE_ID) REFERENCES SUBSCRIPTION_TYPE(SUBSCRIPTION_TYPE_ID);
ALTER TABLE SUBSCRIPTION_PRICE ADD FOREIGN KEY (COUNTRY_ID) REFERENCES CURRENCY(COUNTRY_ID);
ALTER TABLE SUBSCRIPTION_PRICE ADD FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_ID);

